In [1]:
from bs4 import BeautifulSoup
from requests import get
import pandas as pd
import time
from collections import OrderedDict
import re

In [2]:
headers = ({'User-Agent':
            'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36'})

In [3]:
makaan_base="https://www.makaan.com/delhi-residential-property/rent-property-in-delhi-city?page="
makaan_sites =[]
for i in range(1,26):
    makaan_sites.append(makaan_base+str(i))
print(makaan_sites)

['https://www.makaan.com/delhi-residential-property/rent-property-in-delhi-city?page=1', 'https://www.makaan.com/delhi-residential-property/rent-property-in-delhi-city?page=2', 'https://www.makaan.com/delhi-residential-property/rent-property-in-delhi-city?page=3', 'https://www.makaan.com/delhi-residential-property/rent-property-in-delhi-city?page=4', 'https://www.makaan.com/delhi-residential-property/rent-property-in-delhi-city?page=5', 'https://www.makaan.com/delhi-residential-property/rent-property-in-delhi-city?page=6', 'https://www.makaan.com/delhi-residential-property/rent-property-in-delhi-city?page=7', 'https://www.makaan.com/delhi-residential-property/rent-property-in-delhi-city?page=8', 'https://www.makaan.com/delhi-residential-property/rent-property-in-delhi-city?page=9', 'https://www.makaan.com/delhi-residential-property/rent-property-in-delhi-city?page=10', 'https://www.makaan.com/delhi-residential-property/rent-property-in-delhi-city?page=11', 'https://www.makaan.com/delhi-residential-property/rent-property-in-delhi-city?page=12', 'https://www.makaan.com/delhi-residential-property/rent-property-in-delhi-city?page=13', 'https://www.makaan.com/delhi-residential-property/rent-property-in-delhi-city?page=14', 'https://www.makaan.com/delhi-residential-property/rent-property-in-delhi-city?page=15', 'https://www.makaan.com/delhi-residential-property/rent-property-in-delhi-city?page=16', 'https://www.makaan.com/delhi-residential-property/rent-property-in-delhi-city?page=17', 'https://www.makaan.com/delhi-residential-property/rent-property-in-delhi-city?page=18', 'https://www.makaan.com/delhi-residential-property/rent-property-in-delhi-city?page=19', 'https://www.makaan.com/delhi-residential-property/rent-property-in-delhi-city?page=20', 'https://www.makaan.com/delhi-residential-property/rent-property-in-delhi-city?page=21', 'https://www.makaan.com/delhi-residential-property/rent-property-in-delhi-city?page=22', 'https://www.makaan.com/delhi-residential-property/rent-property-in-delhi-city?page=23', 'https://www.makaan.com/delhi-residential-property/rent-property-in-delhi-city?page=24', 'https://www.makaan.com/delhi-residential-property/rent-property-in-delhi-city?page=25']

In [4]:
house_dict=OrderedDict()

In [5]:
for idx1, site in enumerate(makaan_sites):
    response = get(site, headers=headers)
    print("Loading Page {} of Makaan.com".format(idx1))
    print("Getting the respone from website")
    print(response, type(response))
    try:
        html_soup = BeautifulSoup(response.text, 'html.parser')
        house_containers = html_soup.find_all('li', class_="cardholder")

        for idx2, house in enumerate(house_containers):
            house_dict[(idx1+1)*(idx2+1)] = [house.find_all('a')[1].text, house.find_all('a')[2].text, house.find_all('td')[2].text, 
                               house.find_all('td')[4].text, house.find_all('li')[0].text, house.find_all('td')[6].text]
        print("Sleeping For 5 seconds!!")
        time.sleep(5)
        print("**************************************************************")
        print("waking up!!")
    except:
        print("Site not responding!! Try again after some time")
        break

Loading Page 0 of Makaan.com
Getting the respone from website
<Response [200]> <class 'requests.models.Response'>
Sleeping For 5 seconds!!
**************************************************************
waking up!!
Loading Page 1 of Makaan.com
Getting the respone from website
<Response [200]> <class 'requests.models.Response'>
Sleeping For 5 seconds!!
**************************************************************
waking up!!
Loading Page 2 of Makaan.com
Getting the respone from website
<Response [200]> <class 'requests.models.Response'>
Sleeping For 5 seconds!!
**************************************************************
waking up!!
Loading Page 3 of Makaan.com
Getting the respone from website
<Response [200]> <class 'requests.models.Response'>
Sleeping For 5 seconds!!
**************************************************************
waking up!!
Loading Page 4 of Makaan.com
Getting the respone from website
<Response [200]> <class 'requests.models.Response'>
Sleeping For 5 seconds!!
**************************************************************
waking up!!
Loading Page 5 of Makaan.com
Getting the respone from website
<Response [200]> <class 'requests.models.Response'>
Sleeping For 5 seconds!!
**************************************************************
waking up!!
Loading Page 6 of Makaan.com
Getting the respone from website
<Response [200]> <class 'requests.models.Response'>
Sleeping For 5 seconds!!
**************************************************************
waking up!!
Loading Page 7 of Makaan.com
Getting the respone from website
<Response [200]> <class 'requests.models.Response'>
Sleeping For 5 seconds!!
**************************************************************
waking up!!
Loading Page 8 of Makaan.com
Getting the respone from website
<Response [200]> <class 'requests.models.Response'>
Sleeping For 5 seconds!!
**************************************************************
waking up!!
Loading Page 9 of Makaan.com
Getting the respone from website
<Response [200]> <class 'requests.models.Response'>
Sleeping For 5 seconds!!
**************************************************************
waking up!!
Loading Page 10 of Makaan.com
Getting the respone from website
<Response [200]> <class 'requests.models.Response'>
Sleeping For 5 seconds!!
**************************************************************
waking up!!
Loading Page 11 of Makaan.com
Getting the respone from website
<Response [200]> <class 'requests.models.Response'>
Sleeping For 5 seconds!!
**************************************************************
waking up!!
Loading Page 12 of Makaan.com
Getting the respone from website
<Response [200]> <class 'requests.models.Response'>
Sleeping For 5 seconds!!
**************************************************************
waking up!!
Loading Page 13 of Makaan.com
Getting the respone from website
<Response [200]> <class 'requests.models.Response'>
Sleeping For 5 seconds!!
**************************************************************
waking up!!
Loading Page 14 of Makaan.com
Getting the respone from website
<Response [200]> <class 'requests.models.Response'>
Sleeping For 5 seconds!!
**************************************************************
waking up!!
Loading Page 15 of Makaan.com
Getting the respone from website
<Response [200]> <class 'requests.models.Response'>
Sleeping For 5 seconds!!
**************************************************************
waking up!!
Loading Page 16 of Makaan.com
Getting the respone from website
<Response [200]> <class 'requests.models.Response'>
Sleeping For 5 seconds!!
**************************************************************
waking up!!
Loading Page 17 of Makaan.com
Getting the respone from website
<Response [200]> <class 'requests.models.Response'>
Sleeping For 5 seconds!!
**************************************************************
waking up!!
Loading Page 18 of Makaan.com
Getting the respone from website
<Response [200]> <class 'requests.models.Response'>
Sleeping For 5 seconds!!
**************************************************************
waking up!!
Loading Page 19 of Makaan.com
Getting the respone from website
<Response [200]> <class 'requests.models.Response'>
Sleeping For 5 seconds!!
**************************************************************
waking up!!
Loading Page 20 of Makaan.com
Getting the respone from website
<Response [200]> <class 'requests.models.Response'>
Sleeping For 5 seconds!!
**************************************************************
waking up!!
Loading Page 21 of Makaan.com
Getting the respone from website
<Response [200]> <class 'requests.models.Response'>
Sleeping For 5 seconds!!
**************************************************************
waking up!!
Loading Page 22 of Makaan.com
Getting the respone from website
<Response [200]> <class 'requests.models.Response'>
Sleeping For 5 seconds!!
**************************************************************
waking up!!
Loading Page 23 of Makaan.com
Getting the respone from website
<Response [200]> <class 'requests.models.Response'>
Sleeping For 5 seconds!!
**************************************************************
waking up!!
Loading Page 24 of Makaan.com
Getting the respone from website
<Response [200]> <class 'requests.models.Response'>
Sleeping For 5 seconds!!
**************************************************************
waking up!!

In [6]:
pd.DataFrame(house_dict).head()

,1,2,3,4,5,6,7,8,9,10,...,175,250,275,325,350,375,425,450,475,500
0,1 RK Studio Apartment,1 BHK Independent Floor,2 BHK Independent House,1 BHK Independent Floor,3 BHK Independent Floor,1 BHK Apartment,2 BHK Apartment,1 RK Studio Apartment,2 BHK Independent Floor,1 BHK Independent Floor,...,2 BHK Apartment,1 BHK Independent Floor,2 BHK Independent Floor,1 BHK Apartment,2 BHK Independent Floor,2 BHK Independent Floor,2 BHK Apartment,2 BHK Independent Floor,2 BHK Apartment,1 BHK Independent Floor
1,"Vasant Kunj, Delhi","Dwarka Mor, Delhi","Vasant Vihar, Delhi","Sector 13 Dwarka, Delhi","DLF Phase 5, Delhi","Green Park, Delhi","Mayur Vihar II, Delhi","New Ashok Nagar, Delhi","Lajpat Nagar, Delhi","Lajpat Nagar, Delhi",...,"South Extension 1, Delhi","rohini sector 5, Delhi","Sector 25 Rohini, Delhi","Sarita Vihar, Delhi","Chattarpur, Delhi","Tagore Garden Extension, Delhi","SULTANPUR, Delhi","Kapashera, Delhi","Model Town, Delhi","Patel Nagar, Delhi"
2,"9,999","7,500","22,000","14,000","30,000","25,000","21,000","7,200","32,000","8,000",...,"17,000","18,000","18,000","24,000","23,000","23,000","14,000","7,000","21,000","16,000"
3,500,550,750,300,1250,1200,1200,250,990,350,...,800,650,700,800,1000,720,1000,580,891,850
4,No Deposit,No Deposit,No Deposit,No Deposit,No Deposit,No Deposit,No Deposit,No Deposit,No Deposit,No Deposit,...,No Deposit,No Deposit,No Deposit,No Deposit,No Deposit,No Deposit,No Deposit,No Deposit,No Deposit,No Deposit

## Transposing the Data Frame

In [7]:
data = pd.DataFrame(house_dict).T

In [8]:
data.head()

,0,1,2,3,4,5
1,1 RK Studio Apartment,"Vasant Kunj, Delhi","9,999",500,No Deposit,Furnished
2,1 BHK Independent Floor,"Dwarka Mor, Delhi","7,500",550,No Deposit,Semi-Furnished
3,2 BHK Independent House,"Vasant Vihar, Delhi","22,000",750,No Deposit,Semi-Furnished
4,1 BHK Independent Floor,"Sector 13 Dwarka, Delhi","14,000",300,No Deposit,Semi-Furnished
5,3 BHK Independent Floor,"DLF Phase 5, Delhi","30,000",1250,No Deposit,Semi-Furnished

## Adding the columns

In [9]:
data.columns = ["Description_BHK", "Address", "Rent_in_INR", "Area_in_sqft", "Deposit", "Furnish_type"]

In [10]:
data.head()

,Description_BHK,Address,Rent_in_INR,Area_in_sqft,Deposit,Furnish_type
1,1 RK Studio Apartment,"Vasant Kunj, Delhi","9,999",500,No Deposit,Furnished
2,1 BHK Independent Floor,"Dwarka Mor, Delhi","7,500",550,No Deposit,Semi-Furnished
3,2 BHK Independent House,"Vasant Vihar, Delhi","22,000",750,No Deposit,Semi-Furnished
4,1 BHK Independent Floor,"Sector 13 Dwarka, Delhi","14,000",300,No Deposit,Semi-Furnished
5,3 BHK Independent Floor,"DLF Phase 5, Delhi","30,000",1250,No Deposit,Semi-Furnished

## For Changing String to integer

In [11]:
def dep_change(x):
    if x =='No Deposit':
        z= 0.0
    else:
        z = re.sub("[A-Za-z\s\,]", "", x)
        z= float(z)
        if z<10:
            z=z*100000
        else:
            pass
    return z

In [12]:
data['Rent_in_INR']=data['Rent_in_INR'].apply(dep_change)
data['Deposit']=data['Deposit'].apply(dep_change)

## Saving Data in CSV

In [13]:
data.shape

(210, 6)

In [14]:
data_final=data.iloc[:200,:]

In [15]:
data_final.to_csv("Makaan_Delhi.csv", index= False)

In [16]:
data_final.shape

(200, 6)

## No Citations